// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYUye4h-CjFcNwCVVtlPottMNNcZJUU3o',
    appId: '1:66778233764:web:8a86d81ef2531c4aa3df31',
    messagingSenderId: '66778233764',
    projectId: 'agribooking-9f958',
    authDomain: 'agribooking-9f958.firebaseapp.com',
    storageBucket: 'agribooking-9f958.firebasestorage.app',
    measurementId: 'G-BNY5WWRCEY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAbf3aZfqtnrHsj7DFJk_Mp2iaAAKRLLo',
    appId: '1:66778233764:android:95144df534fc077da3df31',
    messagingSenderId: '66778233764',
    projectId: 'agribooking-9f958',
    storageBucket: 'agribooking-9f958.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHRHdot_ySK0cLLcvQBg_Ux3jqFqLJjIE',
    appId: '1:66778233764:ios:1a986aea2aea1466a3df31',
    messagingSenderId: '66778233764',
    projectId: 'agribooking-9f958',
    storageBucket: 'agribooking-9f958.firebasestorage.app',
    iosBundleId: 'com.example.agriBookingApp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHRHdot_ySK0cLLcvQBg_Ux3jqFqLJjIE',
    appId: '1:66778233764:ios:1a986aea2aea1466a3df31',
    messagingSenderId: '66778233764',
    projectId: 'agribooking-9f958',
    storageBucket: 'agribooking-9f958.firebasestorage.app',
    iosBundleId: 'com.example.agriBookingApp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYUye4h-CjFcNwCVVtlPottMNNcZJUU3o',
    appId: '1:66778233764:web:0a43d08753b7a4c0a3df31',
    messagingSenderId: '66778233764',
    projectId: 'agribooking-9f958',
    authDomain: 'agribooking-9f958.firebaseapp.com',
    storageBucket: 'agribooking-9f958.firebasestorage.app',
    measurementId: 'G-G9MND8TN04',
  );
}
